### ISSUE TITLE
Is there a way to use this online?

### ISSUE THREAD

**Issue by Explosion-Scratch** [apple502j/parse-sb3-blocks#1]
Is there a way to port this online?

**Comment by BoomerScratch** [comment]
```html
<script src='https://cdn.jsdelivr.net/npm/parse-sb3-blocks@latest/dist/parse-sb3-blocks.browser.js' defer></script>
```
Here I use `@latest`, but if you want to you can replace `latest` with any version you want. You can also remove `defer`, but I'm not sure if that breaks it.

**Comment by Explosion-Scratch** [comment]
Past me was stupid
