### ISSUE TITLE
Fails to parse sprite

### ISSUE THREAD

**Issue by BirdLogics** [apple502j/parse-sb3-blocks#5]
On the [website](https://apple502j.github.io/parse-sb3-blocks/demo.html), the `Scanner` sprite of the following project fails to parse.

https://scratch.mit.edu/projects/312305395/

Console error message:
```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at parse-sb3-blocks.browser.js:formatted:19286
    at Array.forEach (<anonymous>)
    at p (parse-sb3-blocks.browser.js:formatted:19277)
    at Y (parse-sb3-blocks.browser.js:formatted:19388)
    at parse-sb3-blocks.browser.js:formatted:19281
    at Array.forEach (<anonymous>)
    at p (parse-sb3-blocks.browser.js:formatted:19277)
    at Y (parse-sb3-blocks.browser.js:formatted:19391)
    at O.toScratchblocks (parse-sb3-blocks.browser.js:formatted:19437)
    at demo.js:146
```

**Comment by ksdavidc** [comment]
I am having same error on https://apple502j.github.io/parse-sb3-blocks/demo?pid=716203859&locale=en
with some of the sprites, e.g. SPIDER HP but not others...

[apple502j.github.io-1659116816450.log](https://github.com/apple502j/parse-sb3-blocks/files/9222224/apple502j.github.io-1659116816450.log)

**Comment by ksdavidc** [comment]
minimal example
https://scratch.mit.edu/projects/718002795/

**Comment by ksdavidc** [comment]
Even more minimal. 
this does not work: https://scratch.mit.edu/projects/718004342/
but this does: https://scratch.mit.edu/projects/718004244/editor/

they only differ by by this block
set (pen color v) to {my color}
where my color is a variable.

**Comment by apple502j** [comment]
@ksdavidc Ok, checking.
