### ISSUE TITLE
Takes time to update when project updates. Any way to reset/force update?

### ISSUE THREAD

**Issue by ksdavidc** [apple502j/parse-sb3-blocks#6]
If I load this, then change and save the project, reloading the parser does not reflect the changes, even if cache is cleared.

Is there a way to reset?

**Comment by ksdavidc** [comment]
I waited a few hours and it did update after all. I wonder if there is a way to force an update?

**Comment by apple502j** [comment]
Caching exists and I don't want to bypass it.

**Comment by ksdavidc** [comment]
Understandable. Thanks for responding.
