### ISSUE TITLE
custom blocks have stray backslashes

### ISSUE THREAD

**Issue by ksdavidc** [apple502j/parse-sb3-blocks#7]
In the generator, 
https://apple502j.github.io/parse-sb3-blocks/demo?pid=727789834&locale=en&sprite=Portal

at the bottom, note that certain custom blocks have backslashes in them, and display incorrectly.
`spawn at x: [5080\] y: [50\]::custom`

This happens in Chrome, on a mac latest versions.

**Comment by apple502j** [comment]
Also a custom block named `//` is becoming a comment, this needs upstream consideration
